# Generated by Django 3.0.3 on 2020-08-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=41000, unique=True)),
                ('is_news', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('author', models.IntegerField()),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.Thread')),
            ],
        ),
    ]
