# Generated by Django 3.0.3 on 2020-06-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=25)),
                ('number', models.IntegerField()),
                ('terms', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=41000)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics_identifier.Cluster')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics_identifier.Document')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='reference_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics_identifier.Document'),
        ),
    ]
