# Generated by Django 3.0.3 on 2020-06-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
