# Generated by Django 3.0.3 on 2020-07-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0002_cluster_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics_identifier.Cluster'),
        ),
    ]
