# Generated by Django 3.0.3 on 2020-09-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0010_auto_20200803_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics_identifier.Tree'),
        ),
    ]
