# Generated by Django 3.0.3 on 2020-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0011_auto_20200903_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='reference_document',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
