# Generated by Django 3.0.3 on 2020-09-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_threadtopic_topic'),
        ('topics_identifier', '0013_auto_20200911_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics_identifier.Cluster')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Topic')),
            ],
        ),
    ]
