# Generated by Django 3.0.3 on 2020-09-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0014_clustertopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='num_levels',
            field=models.IntegerField(default=0),
        ),
    ]
