# Generated by Django 3.0.3 on 2020-09-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0015_tree_num_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='num_levels',
            new_name='max_level',
        ),
    ]
