# Generated by Django 3.0.3 on 2020-07-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0004_auto_20200721_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('news', models.BooleanField(default=False)),
                ('comments', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='tree_name',
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.CharField(max_length=41000, unique=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='topics_identifier.Tree'),
            preserve_default=False,
        ),
    ]
