# Generated by Django 3.0.3 on 2020-08-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics_identifier', '0007_auto_20200802_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uri', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateTimeField(default='2020-04-24 19:45:33'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topics_identifier.Thread'),
        ),
    ]
