# Generated by Django 3.0.3 on 2020-08-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
        ('topics_identifier', '0008_auto_20200802_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.Thread'),
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
