# Generated by Django 3.0.3 on 2020-10-19 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_threadtopic_topic'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicannotation',
            name='thread',
        ),
        migrations.AddField(
            model_name='topicannotation',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timeline.Document'),
            preserve_default=False,
        ),
    ]
